
<div class="col-md-12" id="bodyformateurs">
    <section class="row" id="noscours">
        <div class="col-md-4">
            <a href="#" class="thumbnail">
                <img src="<?php $base; ?> ../public/img/2.png" alt="" class="img-rounded">
                <p class="text-center">PHP par Mr Ahmed ADEHAN</p>
            </a>
        </div>
        <div class="col-md-4">
            <a href="#" class="thumbnail">
                <img src="<?php $base; ?> ../public/img/2.png" alt="" class="img-rounded">
                <p class="text-center">PHP par Mr Béthel ATOHOUN</p>
            </a>
        </div>
       
    </section>
</div>
