
<div class="col-md-12" id="bodyformateurs">
    <section class="row" id="noscours">
        <div class="col-md-2 ">
            <a href="<?= $this->url->get('utilisateurs/formateurscathegories'); ?>" class="thumbnail">
                <img src="<?= $this->url->getBaseUri(); ?>public/img/4.png" alt="" class="img-rounded">
                <p class="text-center">Formateurs en PHP</p>
            </a>
        </div>
        <div class="col-md-2 ">
            <a href="#" class="thumbnail">
                <img src="<?= $this->url->getBaseUri(); ?>public/img/4.png" alt="" class="img-rounded">
                <p class="text-center">Formateurs en HTML&CSS</p>
            </a>
        </div>
        <div class="col-md-2">
            <a href="#" class="thumbnail">
                <img src="<?= $this->url->getBaseUri(); ?>public/img/4.png" alt="" class="img-rounded">
                <p class="text-center">Formateurs en Bootstrap</p>
            </a>
        </div>
        <div class="col-md-2">
            <a href="#" class="thumbnail">
                <img src="<?= $this->url->getBaseUri(); ?>public/img/4.png" alt="" class="img-rounded">
                <p class="text-center">Formateurs en Bootstrap</p>
            </a>
        </div>
        <div class="col-md-2">
            <a href="#" class="thumbnail">
                <img src="<?= $this->url->getBaseUri(); ?>public/img/4.png" alt="" class="img-rounded">
                <p class="text-center">Formateurs en Bootstrap</p>
            </a>
        </div>
        <div class="col-md-2">
            <a href="#" class="thumbnail">
                <img src="<?= $this->url->getBaseUri(); ?>public/img/4.png" alt="" class="img-rounded">
                <p class="text-center">Formateurs en Bootstrap</p>
            </a>
        </div>
    </section>
</div>
