
<div class="col-md-12" id="bodyformateurs">
    <section class="row" id="noscours">
        <div class="col-md-2 ">
            <a href="<?= $this->url->get('utilisateurs/formateursdescription'); ?>" class="thumbnail">
                <img src="<?= $this->url->getBaseUri(); ?>public/img/4.png" alt="" class="img-rounded">
                <p class="text-center">Mr Israel DOSSOU</p>
            </a>
        </div>
        <div class="col-md-2 ">
            <a href="#" class="thumbnail">
                <img src="<?= $this->url->getBaseUri(); ?>public/img/4.png" alt="" class="img-rounded">
                <p class="text-center">Mr Giovanni AFFOGLOLO</p>
            </a>
        </div>
        <div class="col-md-2">
            <a href="#" class="thumbnail">
                <img src="<?= $this->url->getBaseUri(); ?>public/img/4.png" alt="" class="img-rounded">
                <p class="text-center">Mr Yann MITCH</p>
            </a>
        </div>
        <div class="col-md-2">
            <a href="#" class="thumbnail">
                <img src="<?= $this->url->getBaseUri(); ?>public/img/4.png" alt="" class="img-rounded">
                <p class="text-center">Mr Farid KEGNIDE</p>
            </a>
        </div>
        <div class="col-md-2">
            <a href="#" class="thumbnail">
                <img src="<?= $this->url->getBaseUri(); ?>public/img/4.png" alt="" class="img-rounded">
                <p class="text-center">Mr Joezer BOURAYIMA</p>
            </a>
        </div>
        <div class="col-md-2">
            <a href="#" class="thumbnail">
                <img src="<?= $this->url->getBaseUri(); ?>public/img/4.png" alt="" class="img-rounded">
                <p class="text-center">Mr Ahmed ADEHAN</p>
            </a>
        </div>
    </section>
</div>
