
<div class="col-md-12" id="bodyformateurs">
    <section class="col-md-5">
        <img id="imageformateur" src="<?php $base; ?> ../public/img/2.png" alt="" class="img-circle">
    </section>
    <section class="col-md-7">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title text-center">INFORMATIONS</h3>
            </div>

            <p class="list-group-item" data-toggle="modal">
                ADEHAN
            </p>

            <p class="list-group-item" data-toggle="modal">
                Ahmed
            </p>

            <p class="list-group-item" data-toggle="modal">
                <a href="<?= $this->url->get('formations/description'); ?>">PHP</a> , <a  href=" <?= $this->url->get('formations/description'); ?>">HTML&CSS</a>
            </p>
        </div>
        <button type="submit" class="btn-success center-block">Voir Plus</button>

    </section>
</div>