
<div class="col-md-12" id="bodyformateurs">
    <section class="row" id="noscours">
        <div class="col-md-2 ">
            <a href="<?= $this->url->get('listeformateurs/index'); ?>" class="thumbnail">
                <img src="<?php $base; ?> ../public/img/4.png" alt="" class="img-rounded">
                <p>Formateurs en PHP</p>
            </a>
        </div>
        <div class="col-md-2 ">
            <a href="#" class="thumbnail">
                <img src="<?php $base; ?> ../public/img/4.png" alt="" class="img-rounded">
                <p>Formateurs en HTML&CSS</p>
            </a>
        </div>
        <div class="col-md-2">
            <a href="#" class="thumbnail">
                <img src="<?php $base; ?> ../public/img/4.png" alt="" class="img-rounded">
                <p>Formateurs en Bootstrap</p>
            </a>
        </div>
        <div class="col-md-2">
            <a href="#" class="thumbnail">
                <img src="<?php $base; ?> ../public/img/4.png" alt="" class="img-rounded">
                <p>Formateurs en Bootstrap</p>
            </a>
        </div>
        <div class="col-md-2">
            <a href="#" class="thumbnail">
                <img src="<?php $base; ?> ../public/img/4.png" alt="" class="img-rounded">
                <p>Formateurs en Bootstrap</p>
            </a>
        </div>
        <div class="col-md-2">
            <a href="#" class="thumbnail">
                <img src="<?php $base; ?> ../public/img/4.png" alt="" class="img-rounded">
                <p>Formateurs en Bootstrap</p>
            </a>
        </div>
    </section>
</div>
