<div class="container">
    <div class="row">

        <div class="col-md-6">
            <div class="page-header">
                <h2>Connexion</h2>
            </div>
            <form action="<?= $this->url->get('index/login'); ?>" method="post">            <fieldset>
                    <div class="form-group">
                        <label for="email">Username/Email</label>
                        <div class="controls">
                            <input type="text" id="email" name="email" value="demo@phalconphp.com" class="form-control" />                    </div>
                    </div>
                    <div class="form-group">
                        <label for="password">Mot de Passe</label>
                        <div class="controls">
                            <input type="password" id="password" name="password" value="phalcon" class="form-control" />                    </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Login" class="btn btn-primary btn-large" />                </div>
                </fieldset>
            </form>
        </div>

        <div class="col-md-6">

            <div class="page-header">
                <h2>Vous n'avez pas encore un compte?</h2>
            </div>

            <p>Créer un compte offre les avantages suivants:</p>
            <ol>
                <li>Créer, suivre des cours en ligne</li>
                <li>Avoir un aperçu des critiques sur la façon dont les formateurs dispences les cours</li>
                <li>Restez informé des nouveau cours et y souscrit</li>
            </ol>

            <div class="clearfix center">
                <a href="<?= $this->url->get('index/inscription'); ?>" class="btn btn-primary btn-large btn-success">Inscription</a>        </div>
        </div>

    </div>
</div>