
<div class="container">

    <!-- Code de la barre de menus de la plateforme-->

    <div id="top" class="container-fluid content">


        <!-- Code des boutons connexion et inscription-->

        <div class="row col-lg-offset-10">
            <div id="html">
                <button data-toggle="modal" data-backdrop="false" href="#connexion" class="btn btn-primary">Connexion</button>
                <button data-toggle="modal" data-backdrop="false" href="#inscription" class="btn btn-primary">Inscription</button>
            </div>

            <!-- Code du formulaire de connexion-->

            <div class="text-center modal fade" id="connexion">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">x</button>
                            <h4 class="modal-title">CONNEXION</h4>
                        </div>
                        <div class="modal-body">
                            <form action="">
                                <div class="form-group">
                                    <input type="text" class="form-control" name ="nom" id="nom" placeholder="Login">
                                </div>
                                <div class="form-group">
                                    <input type="email" class="form-control" name="email" id="email" placeholder="Mot de passe">
                                </div>
                                <div class="text-center">
                                    <button type="submit" class="btn btn-success ">Se connecter</button><br><br>
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button class="btn btn-warning" data-dismiss="modal">Fermer</button>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Code de l'apparition d'une fenêtre modale après clic sur inscription-->

            <div class="modal fade" id="inscription">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">x</button>
                            <h4 class="modal-title">INSCRIPTION</h4>
                        </div>
                        <div class=" text-center modal-body">
                            <button data-toggle="modal" data-backdrop="false" href="#inscriptionetudiant" class="btn btn-primary">Etudiant</button>
                            <button data-toggle="modal" data-backdrop="false" href="#inscriptionenseignant" class="btn btn-primary">Enseignant</button>
                        </div>
                        <div class="modal-footer">
                            <button class="btn btn-warning" data-dismiss="modal">Fermer</button>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Code de l'inscription d'un etudiant-->

            <div class="modal fade" id="inscriptionetudiant">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">x</button>
                            <h4 class="text-center modal-title">ETUDIANT</h4>
                        </div>
                        <div class="modal-body">
                            <form action="">
                                <div class="form-group">
                                    <input type="text" class="form-control" name ="nom" id="nom" placeholder="Nom">
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" name ="prenom" id="prenom" placeholder="Prénom(s)">
                                </div>
                                <div class=" form-control  col-lg-12">
                                    <select class="col-lg-offset-1 col-lg-2" name="jour">	
                                        <?php
                                        for ($i = 0; $i < 31; $i++) {
                                            ?>
                                            <option  value="<?php echo ($i + 1); ?> "><?php echo ($i + 1); ?></option>
                                            <?php
                                        }
                                        ?>
                                    </select>
                                    <select class="col-lg-offset-2 col-lg-2" name="mois">	
                                        <?php
                                        $mois = array('Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Aout', 'Septembre', 'Octobre', 'Novembre', 'Décembre',);
                                        for ($i = 0; $i < 12; $i++) {
                                            ?>
                                            <option value="<?php echo $i + 1; ?>"><?php echo $mois[$i]; ?></option>
                                            <?php
                                        }
                                        ?>
                                    </select>
                                    <select class="col-lg-offset-2 col-lg-2" name="annee">
                                        <?php
                                        for ($i = 1980; $i <= 2050; $i++) {
                                            ?>
                                            <option value="<?php echo $i; ?> "><?php echo $i; ?></option>
                                            <?php
                                        }
                                        ?>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <input type="email" class="form-control" name="email" id="email" placeholder="Email">
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" name ="mot_de_passe" id="mot_de_passe" placeholder="Mot de passe">
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" name ="repeter_mot_de_passe" id="repeter_mot_de_passe" placeholder="Répétez le mot de passe">
                                </div>
                                <div class="text-center">
                                    <button type="submit" class="btn btn-success ">S'inscrire</button><br><br>
                                </div>
                                <div class="text-center">
                                    <a class=" btn btn-primary" href="#">
                                        <p>S'inscrire avec <i class="fa fa-facebook fa-2x">acebook</i></p>
                                    </a> 
                                    <a class="btn btn-danger" href="#">
                                        <p>S'inscrire avec <i class="fa fa-google fa-2x">oogle+</i></p>                                   
                                    </a>
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button class="btn btn-warning" data-dismiss="modal">Fermer</button>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Code de l'inscription d'un enseignant-->

            <div class="modal fade" id="inscriptionenseignant">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">x</button>
                            <h4 class="text-center modal-title">ENSEIGNANT</h4>
                        </div>
                        <div class="modal-body">
                            <form action="">
                                <div class="form-group">
                                    <input type="text" class="form-control" name ="nom" id="nom" placeholder="Nom" required> 
                                </div>
                                <div class="form-group">
                                    <input type="text "class="form-control" name ="prenom" id="prenom" placeholder="Prénom(s)" required>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" name ="date_de_naissance" id="date_de_naissance" placeholder="Date de naissance" required>
                                </div>
                                <div class="form-group">
                                    <input type="email" class="form-control" name="email" id="email" placeholder="Email" required>
                                </div>
                                <div class=" form-control  col-lg-12">
                                    <select class="col-lg-offset-1 col-lg-2" name="jour">	
                                        <?php
                                        for ($i = 0; $i < 31; $i++) {
                                            ?>
                                            <option  value="<?php echo ($i + 1); ?> "><?php echo ($i + 1); ?></option>
                                            <?php
                                        }
                                        ?>
                                    </select>
                                    <select class="col-lg-offset-2 col-lg-2" name="mois">	
                                        <?php
                                        $mois = array('Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Aout', 'Septembre', 'Octobre', 'Novembre', 'Décembre',);
                                        for ($i = 0; $i < 12; $i++) {
                                            ?>
                                            <option value="<?php echo $i + 1; ?>"><?php echo $mois[$i]; ?></option>
                                            <?php
                                        }
                                        ?>
                                    </select>
                                    <select class="col-lg-offset-2 col-lg-2" name="annee">
                                        <?php
                                        for ($i = 1980; $i <= 2050; $i++) {
                                            ?>
                                            <option value="<?php echo $i; ?> "><?php echo $i; ?></option>
                                            <?php
                                        }
                                        ?>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" name ="mot_de_passe" id="mot_de_passe" placeholder="Mot de passe" required>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" name ="repeter_mot_de_passe" id="repeter_mot_de_passe" placeholder="Répétez le mot de passe" required>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" name ="libelle_qualification" id="libelle_qualification" placeholder="Répétez le mot de passe" required>
                                </div>
                                <div class="form-group">
                                    <textarea type="text" class="form-control" name ="description_qualification" id="description_qualification" placeholder="Décrivez votre qualification" required></textarea>
                                </div>
                                <div class="form-group">
                                    <label for="email">Qualification</label>
                                    <input type="file" class="form-control col-lg-6 " name ="fichier_qualification" id="fichier_qualification" placeholder="fichier" required>
                                </div>
                                <div class="text-center">
                                    <button type="submit" class="btn btn-success ">S'inscrire</button><br><br>
                                </div>
                                <div class="text-center">
                                    <a class=" btn btn-primary" href="#">
                                        <p>S'inscrire avec <i class="fa fa-facebook fa-2x">acebook</i></p>
                                    </a> 
                                    <a class="btn btn-danger" href="#">
                                        <p>S'inscrire avec <i class="fa fa-google fa-2x">oogle+</i></p>                                   
                                    </a>
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button class="btn btn-warning" data-dismiss="modal">Fermer</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Code du scrollpy de déroulement fluide vers une portion de la page-->

        <div class="row">
            <section class="col-sm-12">
                <div id="carousel" class="carousel slide">
                    <ol class="carousel-indicators">
                        <li data-target="#carousel" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel" data-slide-to="1"></li>
                        <li data-target="#carousel" data-slide-to="2"></li>
                        <li data-target="#carousel" data-slide-to="3"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="item active"> <img alt="slide" src="<?php $base; ?>public/img/img1.jpg"></div>
                        <div class="item"> <img alt="slide" src="<?php $base; ?>public/img/img2.jpg"></div>
                        <div class="item"> <img alt="slide" src="<?php $base; ?>public/img/img3.jpg"></div>
                        <div class="item"> <img alt="slide" src="<?php $base; ?>public/img/img4.jpg"></div>
                    </div>
                    <a class="left carousel-control" href="#carousel" data-slide="prev">

                        <span class="glyphicon glyphicon-chevron-left"></span>

                    </a>

                    <a class="right carousel-control" href="#carousel" data-slide="next">

                        <span class="glyphicon glyphicon-chevron-right"></span>

                    </a>
                </div>
            </section>
        </div>




        <!-- Code de la portion d'affichage des cours distribués sur le site-->

        <div class="col-lg-12 col-md-12 col-xs-12">
            <section class="row" id="noscours">
                <h1>Quelques Cours</h1>
                <div class="col-xs-6 col-sm-6 col-md-3 ">
                    <a href="#" class="thumbnail">
                        <img src="<?php $base; ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p>Top Python Courses</p>
                    </a>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-3 ">
                    <a href="#" class="thumbnail">
                        <img src="<?php $base; ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p>Top Python Courses</p>
                    </a>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3 ">
                    <a href="#" class="thumbnail">
                        <img src="<?php $base; ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p>Top Python Courses</p>
                    </a>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3 ">
                    <a href="#" class="thumbnail">
                        <img src="<?php $base; ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p>Top Python Courses</p>
                    </a>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3 ">
                    <a href="#" class="thumbnail">
                        <img src="<?php $base; ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p>Top Python Courses</p>
                    </a>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3 ">
                    <a href="#" class="thumbnail">
                        <img src="<?php $base; ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p>Top Python Courses</p>
                    </a>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3 ">
                    <a href="#" class="thumbnail">
                        <img src="<?php $base; ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p>Top Python Courses</p>
                    </a>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3 ">
                    <a href="#" class="thumbnail">
                        <img src="<?php $base; ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p>Top Python Courses</p>
                    </a>
                </div>
            </section>
            <div id="DivClignotante" style="visibility:visible;" class="col-lg-offset-10">
                <a id="clignote" href="noscours.php">Voir plus...</a>
            </div>

        </div>

        <!-- Code de la portion d'affichage des cours les plus suivis sur le système-->

        <div class="col-lg-12 col-md-12 col-xs-12">
            <section class="row" id="lesplussuivis">
                <h1>Les Plus Suivis</h1>
                <div class="col-xs-4 col-sm-6 col-md-8 ">
                    <a href="#" class="thumbnail">
                        <img src="<?php $base; ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p>Top Python Courses</p>
                    </a>

                </div>
                <div class="col-xs-8 col-sm-6 col-md-4">
                    <a href="#" class="thumbnail">
                        <img src="<?php $base; ?> public/img/4.png" alt="slide" class="img-rounded">
                    </a>
                </div>
                <div class="col-xs-8 col-sm-6 col-md-4 ">
                    <a href="#" class="thumbnail">
                        <img src="<?php $base; ?> public/img/4.png" alt="slide" class="img-rounded">
                    </a>
                </div>
            </section>
        </div>
    </div>
</div>

<!-- Scripts et fonctions-->

<script src="<?php $base; ?>public/css/bootstrap/dist/js/jquery.js"></script>
<script src="<?php $base; ?>public/css/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="<?php $base; ?>public/css/bootstrap/dist/js/jquery.min.js"></script>

<!-- Code des fonctions javascript-->

<script>
    //défilement en slide des images
    $(function () {
        $('.carousel').carousel();
    });

             Scrollspy fluide
            $(function () {
            $('nav a').on('click', function (e) {
            e.preventDefault();
            var hash = this.hash;
            $('phtml, body').animate({
            scrollTop: $(this.hash).offset().top
            }, 1000, function () {
            window.location.hash = hash;
            });
            });
            });
    //fonction du formulaire de la fenêtre modale d'inscription
    $(function () {

        $("form").submit(function (e) {
            e.preventDefault();
            var $form = $(this);
            $.post($form.attr("action"), $form.serialize())
                    .done(function (data) {
                        $("#html").html(data);
                        $("#formulaire").modal("hide");
                    })
                    .fail(function () {
                        alert("ça marche pas...");
                    });
        });
    });
    var clignotement = function () {
        if (document.getElementById('DivClignotante').style.visibility == 'visible') {
            document.getElementById('DivClignotante').style.visibility = 'hidden';
        } else {
            document.getElementById('DivClignotante').style.visibility = 'visible';
        }
    };

    // mise en place de l appel de la fonction toutes les 0.8 secondes
    Pour arrêter le clignotement : clearInterval(periode);
            periode = setInterval(clignotement, 800);
</script>
