<div class="container">

    <!-- Code de la barre de menus de la plateforme-->

    <div id="top" class="container-fluid content">

        <!-- Code des boutons connexion et inscription-->

        <div class="row col-lg-offset-10">
            <div id="html">
                <a class="btn btn-primary" href="<?= $this->url->get('index/connexion'); ?>">Connexion</a>
                <a class="btn btn-primary" href="<?= $this->url->get('index/inscription'); ?>">Inscription</a>
            </div>

        </div>

        <!-- Code du slide de défilement des images-->

        <div class="col-sm-12">
            <section>
                <div id="carousel" class="carousel slide">
                    <ol class="carousel-indicators">
                        <li data-target="#carousel" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel" data-slide-to="1"></li>
                        <li data-target="#carousel" data-slide-to="2"></li>
                        <li data-target="#carousel" data-slide-to="3"></li>
                        <li data-target="#carousel" data-slide-to="4"></li>
                        <li data-target="#carousel" data-slide-to="5"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="item active"> <img id="image" alt="slide" src="<?php $this->url->getBaseUri(); ?>public/img/img1.jpg"></div>
                        <div class="item"> <img id="image" alt="slide" src="<?php $this->url->getBaseUri(); ?>public/img/5.jpg"></div>
                        <div class="item"> <img id="image" alt="slide" src="<?php $this->url->getBaseUri(); ?>public/img/6.jpg"></div>
                        <div class="item"> <img id="image" alt="slide" src="<?php $this->url->getBaseUri(); ?>public/img/7.jpg"></div>
                        <div class="item"> <img id="image" alt="slide" src="<?php $this->url->getBaseUri(); ?>public/img/8.jpg"></div>
                        <div class="item"> <img id="image" alt="slide" src="<?php $this->url->getBaseUri(); ?>public/img/9.jpg"></div>
                    </div>
                    <a class="left carousel-control" href="#carousel" data-slide="prev">

                        <span class="glyphicon glyphicon-chevron-left"></span>

                    </a>

                    <a class="right carousel-control" href="#carousel" data-slide="next">

                        <span class="glyphicon glyphicon-chevron-right"></span>

                    </a>
                </div>
            </section>
        </div>




        <!-- Code de la portion d'affichage des cours distribués sur le site-->

        <div class="col-lg-12 col-md-12 col-xs-12">
            <section class="row" id="noscours">
                <h1>Quelques Cours</h1>
                <div class="col-xs-6 col-sm-6 col-md-3 ">
                    <a href="<?= $this->url->get('php/index'); ?>" class="thumbnail">
                        <img src="<?php $this->url->getBaseUri(); ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p class="text-center">PHP</p>
                    </a>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-3 ">
                    <a href="#" class="thumbnail">
                        <img src="<?php $this->url->getBaseUri(); ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p class="text-center">Top Python Courses</p>
                    </a>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3 ">
                    <a href="#" class="thumbnail">
                        <img src="<?php $this->url->getBaseUri(); ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p class="text-center">Top Python Courses</p>
                    </a>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3 ">
                    <a href="#" class="thumbnail">
                        <img src="<?php $this->url->getBaseUri(); ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p class="text-center">Top Python Courses</p>
                    </a>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3 ">
                    <a href="#" class="thumbnail">
                        <img src="<?php $this->url->getBaseUri(); ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p class="text-center">Top Python Courses</p>
                    </a>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3 ">
                    <a href="#" class="thumbnail">
                        <img src="<?php $this->url->getBaseUri(); ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p class="text-center">Top Python Courses</p>
                    </a>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3 ">
                    <a href="#" class="thumbnail">
                        <img src="<?php $this->url->getBaseUri(); ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p class="text-center">Top Python Courses</p>
                    </a>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3 ">
                    <a href="#" class="thumbnail">
                        <img src="<?php $this->url->getBaseUri(); ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p class="text-center">Top Python Courses</p>
                    </a>
                </div>
            </section>
        </div>

        <!-- Code de la portion d'affichage des cours les plus suivis sur le système-->

        <div class="col-lg-12 col-md-12 col-xs-12">
            <section class="row" id="lesplussuivis">
                <h1>Les Plus Suivis</h1>
                <div class="col-xs-4 col-sm-6 col-md-8 ">
                    <a href="#" class="thumbnail">
                        <img src="<?php $this->url->getBaseUri(); ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p class="text-center">Top Python Courses</p>
                    </a>

                </div>
                <div class="col-xs-8 col-sm-6 col-md-4">
                    <a href="#" class="thumbnail">
                        <img alt="Top Python Course" src="<?php $this->url->getBaseUri(); ?> public/img/4.png" alt="slide" class="img-rounded">
                    </a>
                </div>
                <div class="col-xs-8 col-sm-6 col-md-4 ">
                    <a href="#" class="thumbnail">
                        <img alt="Top Python Course" src="<?php $this->url->getBaseUri(); ?> public/img/4.png" alt="slide" class="img-rounded">
                    </a>
                </div>
            </section>
        </div>
    </div>
</div>

<!-- Code des fonctions javascript-->

<script>
    //défilement en slide des images
    $(function () {
        $('.carousel').carousel();
    });

</script>