<div class="container">

    <!-- Code de la barre de menus de la plateforme-->

    <div id="top" class="container-fluid content">

        <!-- Code des boutons connexion et inscription-->

        <div class="row col-lg-offset-10">
            <div id="html">
                <button data-toggle="modal" data-backdrop="false" href="#connexion" class="btn btn-primary">Connexion</button>

                <button data-toggle="modal" data-backdrop="false" href="#inscription" class="btn btn-primary" >Inscription</button>

            </div>

            <!-- Code du formulaire de connexion-->

            <div class="text-center modal fade" id="connexion">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">x</button>
                            <h4 class="modal-title">CONNEXION</h4>
                        </div>
                        <div class="modal-body">
                            <form action="<?= $this->url->get('index/login'); ?>" method="POST">
                                <div class="form-group">
                                    <input type="text" class="form-control" name ="username" id="nom" placeholder="Login">
                                </div>
                                <div class="form-group">
                                    <input type="password" class="form-control" name="secret" id="password" placeholder="Mot de passe">
                                </div>
                                <div class="text-center">
                                    <button type="submit" class="btn btn-success ">Se connecter</button><br>
                                </div>
                                <br>
                                <div class="text-center">
                                    <a class=" btn btn-primary" href="#">
                                        <p>Se Connecter avec <i class="fa fa-facebook fa-2x">acebook</i></p>
                                    </a> 
                                    <a class="btn btn-danger" href="#">
                                        <p>Se Connecter avec <i class="fa fa-google fa-2x">oogle+</i></p>                                   
                                    </a>
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button class="btn btn-warning" data-dismiss="modal">Fermer</button>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Code de l'inscription sur fenetre modale-->

            <div class="modal fade" id="inscription">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">x</button>
                            <h4 class="text-center modal-title">INSCRIPTION</h4>
                        </div>
                        <div class="modal-body">
                            <form action="<?= $this->url->get('index/Singup'); ?>" method="POST">
                                <div class="form-group">
                                    <input type="text" class="form-control" name ="nom" id="nom" placeholder="Nom">
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" name ="prenom" id="prenom" placeholder="Prénom(s)">
                                </div>
                                <div class="form-group">
                                    <input type="email" class="form-control" name="email" id="email" placeholder="Email">
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" name ="mot_de_passe" id="mot_de_passe" placeholder="Mot de passe">
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" name ="repeter_mot_de_passe" id="repeter_mot_de_passe" placeholder="Répétez le mot de passe">
                                </div>
                                <div class="text-center">
                                    <button type="submit" class="btn btn-success ">S'inscrire</button><br><br>
                                </div>
                                <div class="text-center">
                                    <a class=" btn btn-primary" href="#">
                                        <p>S'inscrire avec <i class="fa fa-facebook fa-2x">acebook</i></p>
                                    </a> 
                                    <a class="btn btn-danger" href="#">
                                        <p>S'inscrire avec <i class="fa fa-google fa-2x">oogle+</i></p>                                   
                                    </a>
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button class="btn btn-warning" data-dismiss="modal">Fermer</button>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <!-- Code du slide de défilement des images-->

        <div class="col-sm-12">
            <section>
                <div id="carousel" class="carousel slide">
                    <ol class="carousel-indicators">
                        <li data-target="#carousel" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel" data-slide-to="1"></li>
                        <li data-target="#carousel" data-slide-to="2"></li>
                        <li data-target="#carousel" data-slide-to="3"></li>
                        <li data-target="#carousel" data-slide-to="4"></li>
                        <li data-target="#carousel" data-slide-to="5"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="item active"> <img id="image" alt="slide" src="<?php $this->url->getBaseUri(); ?>public/img/img1.jpg"></div>
                        <div class="item"> <img id="image" alt="slide" src="<?php $this->url->getBaseUri(); ?>public/img/5.jpg"></div>
                        <div class="item"> <img id="image" alt="slide" src="<?php $this->url->getBaseUri(); ?>public/img/6.jpg"></div>
                        <div class="item"> <img id="image" alt="slide" src="<?php $this->url->getBaseUri(); ?>public/img/7.jpg"></div>
                        <div class="item"> <img id="image" alt="slide" src="<?php $this->url->getBaseUri(); ?>public/img/8.jpg"></div>
                        <div class="item"> <img id="image" alt="slide" src="<?php $this->url->getBaseUri(); ?>public/img/9.jpg"></div>
                    </div>
                    <a class="left carousel-control" href="#carousel" data-slide="prev">

                        <span class="glyphicon glyphicon-chevron-left"></span>

                    </a>

                    <a class="right carousel-control" href="#carousel" data-slide="next">

                        <span class="glyphicon glyphicon-chevron-right"></span>

                    </a>
                </div>
            </section>
        </div>




        <!-- Code de la portion d'affichage des cours distribués sur le site-->

        <div class="col-lg-12 col-md-12 col-xs-12">
            <section class="row" id="noscours">
                <h1>Quelques Cours</h1>
                <div class="col-xs-6 col-sm-6 col-md-3 ">
                    <a href="<?= $this->url->get('php/index'); ?>" class="thumbnail">
                        <img src="<?php $this->url->getBaseUri(); ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p class="text-center">PHP</p>
                    </a>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-3 ">
                    <a href="#" class="thumbnail">
                        <img src="<?php $this->url->getBaseUri(); ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p class="text-center">Top Python Courses</p>
                    </a>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3 ">
                    <a href="#" class="thumbnail">
                        <img src="<?php $this->url->getBaseUri(); ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p class="text-center">Top Python Courses</p>
                    </a>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3 ">
                    <a href="#" class="thumbnail">
                        <img src="<?php $this->url->getBaseUri(); ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p class="text-center">Top Python Courses</p>
                    </a>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3 ">
                    <a href="#" class="thumbnail">
                        <img src="<?php $this->url->getBaseUri(); ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p class="text-center">Top Python Courses</p>
                    </a>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3 ">
                    <a href="#" class="thumbnail">
                        <img src="<?php $this->url->getBaseUri(); ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p class="text-center">Top Python Courses</p>
                    </a>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3 ">
                    <a href="#" class="thumbnail">
                        <img src="<?php $this->url->getBaseUri(); ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p class="text-center">Top Python Courses</p>
                    </a>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3 ">
                    <a href="#" class="thumbnail">
                        <img src="<?php $this->url->getBaseUri(); ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p class="text-center">Top Python Courses</p>
                    </a>
                </div>
            </section>
            <div id="DivClignotante" style="visibility:visible;" class="col-lg-offset-10">
                <a id="clignote" href="<?= $this->url->get('noscours/index'); ?>">Voir plus...</a>
            </div>

        </div>

        <!-- Code de la portion d'affichage des cours les plus suivis sur le système-->

        <div class="col-lg-12 col-md-12 col-xs-12">
            <section class="row" id="lesplussuivis">
                <h1>Les Plus Suivis</h1>
                <div class="col-xs-4 col-sm-6 col-md-8 ">
                    <a href="#" class="thumbnail">
                        <img src="<?php $this->url->getBaseUri(); ?> public/img/4.png" alt="slide" class="img-rounded">
                        <p class="text-center">Top Python Courses</p>
                    </a>

                </div>
                <div class="col-xs-8 col-sm-6 col-md-4">
                    <a href="#" class="thumbnail">
                        <img alt="Top Python Course" src="<?php $this->url->getBaseUri(); ?> public/img/4.png" alt="slide" class="img-rounded">
                    </a>
                </div>
                <div class="col-xs-8 col-sm-6 col-md-4 ">
                    <a href="#" class="thumbnail">
                        <img alt="Top Python Course" src="<?php $this->url->getBaseUri(); ?> public/img/4.png" alt="slide" class="img-rounded">
                    </a>
                </div>
            </section>
        </div>
    </div>
</div>

<!-- Code des fonctions javascript-->

<script>
    //défilement en slide des images
    $(function () {
        $('.carousel').carousel();
    });

    Scrollspy
    fluide
    $(function () {
        $('nav a').on('click', function (e) {
            e.preventDefault();
            var hash = this.hash;
            $('phtml, body').animate({
                scrollTop: $(this.hash).offset().top
            }, 1000, function () {
                window.location.hash = hash;
            });
        });
    });
    //fonction du formulaire de la fenêtre modale d'inscription
    $(function () {

        $("form").submit(function (e) {
            e.preventDefault();
            var $form = $(this);
            $.post($form.attr("action"), $form.serialize())
                    .done(function (data) {
                        $("#html").html(data);
                        $("#formulaire").modal("hide");
                    })
                    .fail(function () {
                        alert("ça marche pas...");
                    });
        });
    });
    var clignotement = function () {
        if (document.getElementById('DivClignotante').style.visibility == 'visible') {
            document.getElementById('DivClignotante').style.visibility = 'hidden';
        } else {
            document.getElementById('DivClignotante').style.visibility = 'visible';
        }
    };

    // mise en place de l appel de la fonction toutes les 0.8 secondes
    //Pour
    //arrêter le clignotement : clearInterval(periode);
    periode = setInterval(clignotement, 800);
</script>

<!--
<script src="<?= $this->url->getBaseUri(); ?>public/vendor/jquery/dist/jquery.js" ></script>
<script src="<?= $this->url->getBaseUri(); ?>public/vendor/jquery/dist/jquery.min.js"></script>
<script src="<?= $this->url->getBaseUri(); ?>public/vendor/bootstrap/dist/js/bootstrap.min.js"></script>      
<script src="<?= $this->url->getBaseUri(); ?>public/vendor/bootstrap/js/carousel.js"></script>
<script src="<?= $this->url->getBaseUri(); ?>public/vendor/bootstrap/js/scrollspy.js"></script>-->