<nav class="navbar navbar-inverse navbar-fixed-top" style="back">

    <ul class="nav navbar-nav">
        <li class="active"><a href="<?= $this->url->get(''); ?>">FVL#79</a></li>
        <li><a href="#page-top"></a></li>
        <li><a href="#noscours">Cours</a></li>
        <li><a href="#lesplussuivis">Les plus suivis</a></li>
        <li><a href="<?= $this->url->get('utilisateurs/formateurs'); ?>">Formateurs</a></li>
    </ul>
    <form class="navbar-form navbar-right inline-form">
        <div class="form-group">
            <input type="search" class="input-sm form-control" placeholder="Recherche">
            <button type="submit" class="btn btn-primary btn-sm"><span class="glyphicon glyphicon-eye-open"></span>Chercher</button>
        </div>
    </form>

</nav>