<div class="row center-block">
    <div class="col-md-12 center-block" id="droite">
        <h2>Créer une formation</h2>
        <div>
            <form action="ajout" method="POST">
                <div class="form-group">
                    <input type="text" class="form-control" name ="libelle_formation" id="libelle_formation" placeholder="Libellé Formation">
                </div>
                <div class="form-group">
                    <textarea type="text" class="form-control" name ="description_formation" id="description_formation" placeholder="Description Formation"></textarea>
                </div>
                <div class="form-group">
                    <input type="number" class="form-control" name ="cout_formation" id="cout_formation" placeholder="Cout Formation">
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-success ">Créer</button>
                    <button type="reset" class="btn btn-danger ">Annuler</button>

                </div>
            </form>
        </div>
    </div>
</div>