<div class="container">
    <div class="jumbotron text-center">
        <h1>Bienvenu sur le cours de PHP</h1>
        <p>Le language PHP est un language qui permet de rendre vos page dynamique et en autres d'optiniser ces derniers.</p>
        <p>Ce cours est dispensé par <a href="<?= $this->url->get('utilisateurs/formateursdescription'); ?>">Mr Israel DOSSOU</a></p>
    </div>


    <div class="row">
        <div class="col-md-4">
            <h2>Chapitre N°1</h2>
            <ol>
                <li><a href="#">Les Variable</a></li>
                <li><a href="#">Les structures de conditions</a></li>
                <li><a href="#">Les strutures de boucles</a></li>
            </ol>
        </div>
        <div class="col-md-4">
            <h2>Chapitre N°2</h2>
            <ol>
                <li><a href="#">Les requetes</a></li>
                <li><a href="#">Les expressions regulieres</a></li>
                <li><a href="#">Les fonctions</a></li>
            </ol>
        </div>
        <div class="col-md-4">
           <h2>Chapitre N°3</h2>
            <ol>
                <li><a href="#">Manipulation de PDO</a></li>
                <li><a href="#">Php Orienté Objet</a></li>
                <li>Quiz de fin de formation</a></a></li>
            </ol>
        </div>
    </div>

    <button type="submit" value="Suivre ce Cours" class="center-block btn-success">Suivre ce Cours</button>
</div>