
<div class="col-md-12" id="bodyformateurs">
    <section class="row" id="noscours">
        <div class="col-md-2">
            <a href="<?= $this->url->get('formations/description'); ?>" class="thumbnail">
                <img src="<?= $this->url->getBaseUri(); ?>public/img/2.png" alt="" class="img-rounded">
                <p class="text-center">PHP</p>
            </a>
        </div>
        <div class="col-md-2">
            <a href="<?= $this->url->get(''); ?>" class="thumbnail">
                <img src="<?= $this->url->getBaseUri(); ?>public/img/2.png" alt="" class="img-rounded">
                <p class="text-center">HTML & CSS</p>
            </a>
        </div>
        <div class="col-md-2">
            <a href="<?= $this->url->get(''); ?>" class="thumbnail">
                <img src="<?= $this->url->getBaseUri(); ?>public/img/2.png" alt="" class="img-rounded">
                <p class="text-center">HTML & CSS</p>
            </a>
        </div>
        <div class="col-md-2">
            <a href="<?= $this->url->get(''); ?>" class="thumbnail">
                <img src="<?= $this->url->getBaseUri(); ?>public/img/2.png" alt="" class="img-rounded">
                <p class="text-center">HTML & CSS</p>
            </a>
        </div>
        <div class="col-md-2">
            <a href="<?= $this->url->get(''); ?>" class="thumbnail">
                <img src="<?= $this->url->getBaseUri(); ?>public/img/2.png" alt="" class="img-rounded">
                <p class="text-center">HTML & CSS</p>
            </a>
        </div>
        <div class="col-md-2">
            <a href="<?= $this->url->get(''); ?>" class="thumbnail">
                <img src="<?= $this->url->getBaseUri(); ?>public/img/2.png" alt="" class="img-rounded">
                <p class="text-center">HTML & CSS</p>
            </a>
        </div>

    </section>
</div>
