<!DOCTYPE html>
<html>
    <head>
        <title> FLV#79 </title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="" rel="stylesheet">
        <link href="<?= $this->url->getBaseUri(); ?>public/vendor/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
        <link href="<?= $this->url->getBaseUri(); ?>public/vendor/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="<?= $this->url->getBaseUri(); ?>public/vendor/font-awesome/css/font-awesome.css" rel="stylesheet">
        <link href="<?= $this->url->getBaseUri(); ?>public/css/Style.css" rel="stylesheet">

    </head>
    <body  data-spy="scroll" data-target=".navbar">

        <?php
        /* if(!isset($menuView)) {
          $menuView = "partials/menu_default";
          } */
        $menu = new Elements();
        $this->partial($menu->getMenu());
        ?>

        <?php echo $this->getContent(); ?>

        <hr>
        <footer class="container text-center">
            <p>&copy; Company FLV#79 2016 
                <a class="btn btn-primary" href="#"><i class="fa fa-twitter fa-2x "></i></a>
                <a class="btn btn-primary " href="#"><i class="fa fa-facebook fa-2x "></i></a>
                <a class="btn btn-danger"href="#"><i class="fa fa-google-plus fa-2x "></i></a>
                <a class="btn btn-primary " href="#"><i class="fa fa-youtube fa-2x "></i></a>
                <a class="btn btn-success" href="#"><i class="fa fa-linkedin fa-2x "></i></a>
                <a class="btn btn-danger"href="#"><i class="fa fa-github fa-2x "></i></a>
            </p>
        </footer>

        <script src="<?= $this->url->getBaseUri(); ?>public/vendor/jquery/dist/jquery.js" ></script>
        <script src="<?= $this->url->getBaseUri(); ?>public/vendor/jquery/dist/jquery.min.js"></script>
        <script src="<?= $this->url->getBaseUri(); ?>public/vendor/bootstrap/dist/js/bootstrap.min.js"></script>      
        <script src="<?= $this->url->getBaseUri(); ?>public/vendor/bootstrap/js/carousel.js"></script>
        <script src="<?= $this->url->getBaseUri(); ?>public/vendor/bootstrap/js/scrollspy.js"></script>

    </body>
</html>